version: "3.3"
services:
    # Silab multiprotocol
    multipan:
        container_name: multipan
        image: "homeassistant/aarch64-addon-silabs-multiprotocol:1.3.0"
        env_file: .env
        cap_add:
          - SYS_ADMIN
          - NET_ADMIN
        restart: always
        privileged: true
        network_mode: host
        build: ./
